### ISSUE TITLE
运行后只提示服务器安装完成

### ISSUE THREAD

**Issue by flycat233** [44578287/PalWorldServerTool#1]
没有后续界面了，也没有启动服务器

**Comment by 44578287** [comment]
https://github.com/44578287/PalWorldServerTool/releases/tag/1.1.1
更新了V1.1.1版本，哥们你再试试

**Comment by flycat233** [comment]
感谢更新

**Comment by flycat233** [comment]
还有一个BUG需要反馈，在运行软件后，服务端确实起来了，但是会自动重置配置文件，修改配置文件后一旦运行软件启动服务器，配置文件就会被重置为默认配置

**Comment by 44578287** [comment]
您可以提供下日志以及您修改的配置吗?

**Comment by flycat233** [comment]
2024/10/2 1:40:13 [ Infor ] -> Log Start...
**********************************************************************************************************************
                                                                                                                     
                                                        快易享                                                          
                            项目发布地址 @ https://445720.xyz and https://github.com/44578287                              
                                     ck呵呵 QQ:2407896713 mail:g9964957@gmail.com                                      
                                                                                                                     
**********************************************************************************************************************

2024/10/2 1:40:13 [ Debug ] -> 加载PalGameWorldSettings.ini文件: Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=5.000000,PalCaptureRate=3.000000,PalSpawnNumRate=2.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=3.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=0.200000,PlayerStaminaDecreaceRate=0.200000,PlayerAutoHPRegeneRate=2.000000,PlayerAutoHpRegeneRateInSleep=2.000000,PalStomachDecreaceRate=0.500000,PalStaminaDecreaceRate=0.500000,PalAutoHPRegeneRate=2.000000,PalAutoHpRegeneRateInSleep=2.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=3.000000,CollectionObjectHpRate=0.500000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=2.000000,DeathPenalty=None,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=True,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampMaxNumInGuild=4,BaseCampWorkerMaxNum=25,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=0.000000,WorkSpeedRate=2.500000,AutoSaveSpan=30,AllowConnectPlatform=Steam,LogFormatType=Text,bIsMultiplay=True,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=False,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,bShowPlayerList=True,CoopPlayerMaxNum=4,ServerPlayerMaxNum=32,ServerName="????????????|????|????|PVE",ServerDescription="????????????|????|????|PVE",AdminPassword="wlf123",ServerPassword="",PublicPort=8211,PublicIP="",RCONEnabled=True,RCONPort=25575,RESTAPIEnabled=True,RESTAPIPort=8212,bIsUseBackupSaveData=True,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt",SupplyDropSpan=180
2024/10/2 1:40:13 [ Error ] -> PalWorldSettingsDataModel.cs > Load() > in line[384]: 加载PalGameWorldSettings.ini文件时发生错误 因为:Sequence contains no elements
2024/10/2 1:40:13 [ Infor ] -> PalWorldServer => 服务器配置文件加载失败 重新创建
2024/10/2 1:40:13 [ Debug ] -> 加载PalGameWorldSettings.ini文件: 
2024/10/2 1:40:13 [ Infor ] -> PalWorldServer => 服务器RCON密码为空 重新创建
2024/10/2 1:40:13 [ Infor ] -> PalWorldServer => 服务器配置文件加载成功
2024/10/2 1:40:13 [ Debug ] -> PalWorldServerPerformanceMonitorOutput=>已创建
2024/10/2 1:40:13 [ Debug ] -> PalWorldServerPerformanceMonitorOutput=>已初始化
2024/10/2 1:40:13 [ Infor ] -> PalWorldServer => 启动服务器
2024/10/2 1:40:13 [ Debug ] -> 进程采集任务 ID:5336 Name:"PalServer-Win64-Shipping-Cmd" =>已创建
2024/10/2 1:40:13 [ Debug ] -> 进程采集任务 ID:5336 Name:"PalServer-Win64-Shipping-Cmd" =>已初始化
2024/10/2 1:40:13 [ Debug ] -> 进程采集任务 ID:5336 Name:"PalServer-Win64-Shipping-Cmd" =>已执行初始化任务
2024/10/2 1:40:13 [ Debug ] -> 进程采集任务 ID:5336 Name:"PalServer-Win64-Shipping-Cmd" =>已开始执行任务
2024/10/2 1:40:13 [ Debug ] -> PalWorldServerPerformanceMonitorOutput=>已执行初始化任务
2024/10/2 1:40:13 [ Debug ] -> PalWorldServerPerformanceMonitorOutput=>已开始执行任务
2024/10/2 1:40:14 [ Warn  ] -> PalWorldServer => Setting breakpad minidump AppID = 1623730
2024/10/2 1:40:14 [ Infor ] -> PalWorldServer => 等待连接RCON: 127.0.0.1:25575
2024/10/2 1:40:15 [ Error ] -> PalWorldServer.cs > RconInitialization() > in line[506]: PalWorldServer => RCON连接失败 因为:由于目标计算机积极拒绝，无法连接。
2024/10/2 1:40:15 [ Infor ] -> PalWorldServer => RCON尝试重新连接第1次
2024/10/2 1:40:19 [ Error ] -> PalWorldServer.cs > RconInitialization() > in line[506]: PalWorldServer => RCON连接失败 因为:由于目标计算机积极拒绝，无法连接。
2024/10/2 1:40:19 [ Infor ] -> PalWorldServer => RCON尝试重新连接第2次
2024/10/2 1:40:23 [ Error ] -> PalWorldServer.cs > RconInitialization() > in line[506]: PalWorldServer => RCON连接失败 因为:由于目标计算机积极拒绝，无法连接。
2024/10/2 1:40:23 [ Infor ] -> PalWorldServer => RCON尝试重新连接第3次

配置文件是用的网页在线生成的，直接运行帕鲁是可以识别的

**Comment by 44578287** [comment]
哥们修好了，才发现之前配置文件的读取那部份做的有问题，这次建议删除Config.json重新配置
https://github.com/44578287/PalWorldServerTool/releases/tag/1.1.2

**Comment by flycat233** [comment]
感谢吖大佬，麻烦您了
